package nativelib.interception

object InterceptionFilter {

    const val INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN = 0x001
    const val INTERCEPTION_MOUSE_LEFT_BUTTON_UP = 0x002
    const val INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN = 0x004
    const val INTERCEPTION_MOUSE_RIGHT_BUTTON_UP = 0x008
    const val INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN = 0x010
    const val INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP = 0x020

    const val INTERCEPTION_FILTER_KEYBOARD_ESC = 0x01
    const val INTERCEPTION_FILTER_KEYBOARD_0 = 0x0B
    const val INTERCEPTION_FILTER_KEYBOARD_1 = 0x02
    const val INTERCEPTION_FILTER_KEYBOARD_2 = 0x03
    const val INTERCEPTION_FILTER_KEYBOARD_3 = 0x04
    const val INTERCEPTION_FILTER_KEYBOARD_4 = 0x05
    const val INTERCEPTION_FILTER_KEYBOARD_5 = 0x06
    const val INTERCEPTION_FILTER_KEYBOARD_6 = 0x07
    const val INTERCEPTION_FILTER_KEYBOARD_7 = 0x08
    const val INTERCEPTION_FILTER_KEYBOARD_8 = 0x09
    const val INTERCEPTION_FILTER_KEYBOARD_9 = 0x0A
}